# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Hillside52 nice_nano_v2 nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["hillside52_left nice_view_adapter nice_view","hillside52_right nice_view_adapter nice_view"]'
      custom_config: '["#define MIRYOKU_ALPHAS_QWERTY","#define MIRYOKU_MAPPING_EXTENDED_THUMBS","#define MIRYOKU_NAV=VI","#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y","CONFIG_ZMK_MOUSE=y"]'
      branches: '["burgessa23/zmk/animated_widgets"]'
